### ISSUE TITLE
rubymotion 3.14, this doesn't work

### ISSUE THREAD

**Issue by h1u2i3** [darinwilson/motion-async#1]

**Comment by darinwilson** [comment]
Hi @h1u2i3 - unfortunately there a lot of issues with RubyMotion 3.14 on Android that make it pretty much unusable. HipByte is aware of this, but there's no telling when there will be a fix in place. For now, the best solution is to roll back to version 3.13:

`sudo motion update --cache-version=3.13`

I'll keep this issue open, just in case there is another separate problem with motion-async, but it appears that the problem is with RubyMotion itself, not the gem.

**Comment by darinwilson** [comment]
This appears to be stale - closing.
